config/routes.rb
Rails.application.routes.draw do
  root 'requisitions#index'

  resources :sessions, only: [:new]

  resources :profiles, only: [:new, :create]

  resources :requisitions, except: [:destroy]

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
end

app/models/personal_reference.rb
class PersonalReference < ActiveRecord::Base
  belongs_to :requisition

  validates :first_name,
    :second_name,
    :first_last_name,
    :second_last_name,
    :cell_phone_number,
    presence: true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates :first_name,
    :second_name,
    :second_last_name,
    :first_last_name,
    :birth_date,
    :curp,
    :rfc,
    :gender,
    :birth_state,
    :phone_number,
    :email,
    presence: true

  validates :email,
    :rfc,
    :curp,
    uniqueness: true
end

app/models/requisition.rb
class Requisition < ActiveRecord::Base
  belongs_to :user
  has_many :personal_references

  validates :income,
    :address_years,
    :company_years,
    :marital_status,
    :requested_amount,
    :payment_terms,
    :bank,
    :comment,
    :company_name,
    :company_phone_number,
    :dependents_number,
    :company_position,
    presence: true

  accepts_nested_attributes_for :personal_references
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :profile
  has_many :requisitions
  validates :name,
    :facebook_id,
    :oauth_token,
    :oauth_expires_at,
    presence: true

  class << self
    def facebook_authenticate(auth)
      where(facebook_id: auth[:uid]).first_or_initialize.tap do |user|
        user.facebook_id = auth.uid
        user.name = auth.info.name
        user.oauth_token = auth.credentials.token
        user.oauth_expires_at = Time.at(auth.credentials.expires_at)
        user.save!
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authenticable
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/concerns/authenticable.rb
module Authenticable
  def authenticate_user!
    redirect_to new_session_path unless user_signed_in?
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end

  def public_profile
    facebook_connection = Koala::Facebook::API.new(current_user.oauth_token)
    return {} if facebook_connection.app_secret.nil?
    facebook_connection.get_object("me?fields=first_name,birthday,email,gender")
  end

  private
  def user_signed_in?
    session[:user_id].present?
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new(public_profile)
  end

  def create
    @profile = current_user.create_profile(profile_params)
    if @profile.save
      redirect_to root_path
    else
      render action: "new"
    end
  end

  private

  def profile_params
    params.require(:profile).permit(
      :first_name,
      :second_name,
      :second_last_name,
      :first_last_name,
      :birth_date,
      :curp,
      :rfc,
      :gender,
      :birth_date,
      :phone_number,
      :email,
      :birth_state
    )
  end
end

app/controllers/requisitions_controller.rb
class RequisitionsController < ApplicationController
  def index
    @requisitions = current_user.requisitions
  end

  def new
    @requisition = current_user.requisitions.build
  end

  def create
    @requisition = current_user.requisitions.build(requisition_params)
    if @requisition.save
      redirect_to root_path
    else
      render action: "new"
    end
  end

  def edit
    @requisition = current_user.requisitions.find(params[:id])
  end

  def update
    @requisition = current_user.requisitions.find(params[:id])
    if @requisition.update_attributes(requisition_params)
      redirect_to root_path
    else
      render 'edit'
    end
  end

  private

  def requisition_params
    params.require(:requisition).permit(
      :income,
      :address_years,
      :company_years,
      :marital_status,
      :requested_amount,
      :payment_terms,
      :bank,
      :comment,
      :company_name,
      :company_phone_number,
      :dependents_number,
      :company_position,
      :has_sgmm,
      :has_imss,
      :has_car,
      personal_references_attributes: [
        :first_name,
        :second_name,
        :first_last_name,
        :second_last_name,
        :cell_phone_number
      ]
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def create
    @user = register_user
    session[:user_id] = @user.id
    return redirect_to new_profile_path unless has_profile?
    redirect_to root_path
  end

  private

  def register_user
    User.facebook_authenticate(request.env["omniauth.auth"])
  end

  def has_profile?
    @user.profile.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def boolean_options
    {"SI" => true, "NO" => false}
  end

  def current_user
    @current_user ||= User.find(session[:user_id])
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def curp_regex
    "[A-Z]{1}[AEIOU]{1}[A-Z]{2}[0-9]{2}" +
    "(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])" +
    "[HM]{1}" +
    "(AS|BC|BS|CC|CS|CH|CL|CM|DF|DG|GT|GR|HG|JC|MC|MN|MS|NT|NL|OC|PL|QT|QR|SP|SL|SR|TC|TS|TL|VZ|YN|ZS|NE)" +
    "[B-DF-HJ-NP-TV-Z]{3}" +
    "[0-9A-Z]{1}[0-9]{1}$"
  end

  def rfc_regex
    "[A-Z]{1}[AEIOU]{1}[A-Z]{2}"+
    "[0-9]{2}(0[1-9]|1[0-2])(0[1-9]|1[0-9]|2[0-9]|3[0-1])"
  end

  def gender_options
    {'Masculino' => 'male', 'Femenino' => 'female'}
  end
end

app/helpers/requisitions_helper.rb
module RequisitionsHelper
  def welcome_message
    if @requisitions.empty?
      t('requisitions.messages.empty_requisitions')
    else
      current_user.name
    end
  end

  def options_of_marital_status
    {'Soltero' => 'single', 'Casado' => 'married'}
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YtpTest</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= yield :javascript_bottom %>
</html>

app/views/personal_references/_form.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="personal-references-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= t('personal_references.messages.title') %></h4>
      </div>
      <div class="modal-body">
        <%= form_tag('#') do %>
          <h3 id="form_errors"></h3>
          <div class="form-group">
            <label class="control-label"><%= t('personal_references.fields.first_name') %></label>
            <%= text_field :first_name, nil, class: 'form-control', 'data-bind' => 'value: first_name'%>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('personal_references.fields.second_name') %></label>
            <%= text_field :second_name, nil, class: 'form-control', 'data-bind' => 'value: second_name'%>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('personal_references.fields.first_last_name') %></label>
            <%= text_field :first_last_name, nil, class: 'form-control', 'data-bind' => 'value: first_last_name'%>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('personal_references.fields.second_last_name') %></label>
            <%= text_field :second_last_name, nil, class: 'form-control', 'data-bind' => 'value: second_last_name'%>
            <div class="help-block with-errors"></div>
          </div>
          <div class="form-group">
            <label class="control-label"><%= t('personal_references.fields.cell_phone_number') %></label>
            <%= telephone_field :cell_phone_number, nil, class: 'form-control', 'data-bind' => 'value: cell_phone_number'%>
            <div class="help-block with-errors"></div>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
        <button type="button" class="btn btn-primary" data-bind="click: addPersonalReference"><%= t('personal_references.messages.adds') %></button>
      </div>
    </div>
  </div>
</div>
</div>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: {action: "create"}, html: {'data-toggle' => "validator"} do |f| %>
  <div class="form-group">
    <label class="control-label"><%= t('profiles.fields.first_name') %></label>
    <%= f.text_field :first_name, required: true, class: 'form-control'%>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('profiles.fields.second_name') %></label>
    <%= f.text_field :second_name, required: true, class: 'form-control' %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('profiles.fields.first_last_name') %></label>
    <%= f.text_field :first_last_name, required: true, class: 'form-control' %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('profiles.fields.second_last_name') %></label>
    <%= f.text_field :second_last_name, required: true, class: 'form-control' %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('profiles.fields.birth_date') %></label>
    <%= f.date_field :birth_date, required: true, class: 'form-control', pattern: "^[_A-z0-9]{1,}$" %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('profiles.fields.curp') %></label>
    <%= f.text_field :curp, required: true, class: 'form-control uppercase', pattern: curp_regex %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('profiles.fields.rfc') %></label>
    <%= f.text_field :rfc, required: true, class: 'form-control uppercase', pattern: rfc_regex %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('profiles.fields.gender') %></label>
    <%= f.select(:gender, options_for_select(gender_options), { include_blank: '', required: true }, { class: 'form-control' }) %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('profiles.fields.birth_state') %></label>
    <%= f.text_field :birth_state, class: 'form-control', required: true%>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('profiles.fields.phone_number') %></label>
    <%= f.telephone_field :phone_number, class: 'form-control', required: true %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('profiles.fields.email') %></label>
    <%= f.email_field :email, class: 'form-control', required: true %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <%= f.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-12">
    <h2 class="bd-title"><%= t('profiles.messages.new') %></h2>
  </div>
</div>
<div class="row">
  <div class="col-12 col-md-9 pull-md-3 bd-content">
    <%= render "form" %>
  </div>
</div>

app/views/requisitions/_form.html.erb
<%= form_for @requisition,  html: {'data-toggle' => "validator"} do |f| %>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.income') %></label>
    <%= f.number_field :income, required: true, class: 'form-control'%>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.address_years') %></label>
    <%= f.number_field :address_years, required: true, class: 'form-control' %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.company_years') %></label>
    <%= f.number_field :company_years, required: true, class: 'form-control' %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.marital_status') %></label>
    <%= f.select(:marital_status, (options_of_marital_status), { include_blank: '' }, { class: 'form-control' , required: true}) %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.requested_amount') %></label>
    <%= f.number_field :requested_amount, required: true, class: 'form-control' %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.payment_terms') %></label>
    <%= f.text_field :payment_terms, required: true, class: 'form-control' %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.bank') %></label>
    <%= f.text_field :bank, required: true, class: 'form-control' %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.comment') %></label>
    <%= f.text_field :comment, required: true, class: 'form-control' %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.company_name') %></label>
    <%= f.text_field :company_name, class: 'form-control', required: true%>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.company_phone_number') %></label>
    <%= f.telephone_field :company_phone_number, class: 'form-control', required: true %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.dependents_number') %></label>
    <%= f.number_field :dependents_number, class: 'form-control', required: true %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.company_position') %></label>
    <%= f.text_field :company_position, class: 'form-control', required: true %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.has_sgmm') %></label>
    <%= f.select(:has_sgmm, (boolean_options), { include_blank: '' }, { class: 'form-control' , required: true }) %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.has_imss') %></label>
    <%= f.select(:has_imss, (boolean_options), { include_blank: ''}, { class: 'form-control' , required: true }) %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><%= t('requisitions.fields.has_car') %></label>
    <%= f.select(:has_car, (boolean_options), { include_blank: '' }, { class: 'form-control', required: true }) %>
    <div class="help-block with-errors"></div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <h2 class="bd-title"><%= t('personal_references.messages.title') %></h2>
    </div>
    <div class="col-md-2">
      <h3 data-bind="text: items().length+ ' de 3'"></h3>
    </div>
    <div class="col-md-4">
      </br>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#personal-references-modal"> <%= t('personal_references.messages.adds') %> </button>
    </div>
  </div>
  <div class="row">
    <div id="itemPersonalReferences" class="hidden">
  </div>
  <div class="row">
    <table class="table table-striped">
      <thead>
        <th><%= t('personal_references.fields.first_name') %></th>
        <th><%= t('personal_references.fields.second_name') %></th>
        <th><%= t('personal_references.fields.second_last_name') %></th>
        <th><%= t('personal_references.fields.cell_phone_number') %></th>
      </thead>
      <tbody data-bind="foreach: items">
        <tr>
          <td data-bind="text: first_name"></td>
          <td data-bind="text: second_name"></td>
          <td data-bind="text: first_last_name"></td>
          <td data-bind="text: second_last_name"></td>
          <td data-bind="text: cell_phone_number"></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="form-group">
    <%= f.submit "Create", class: "btn btn-primary", "data-bind" => "enable: items().length >= 3" %>
  </div>
<% end %>

<%= render partial: "personal_references/form" %>

app/views/requisitions/edit.html.erb
<div class="row">
  <div class="col-12">
    <h2 class="bd-title"><%= t('requisitions.messages.new_instructions') %></h2>
  </div>
</div>
<div class="row">
  <div class="col-12 col-md-9 pull-md-3 bd-content">
    <%= render "form" %>
  </div>
</div>
<% content_for :javascript_bottom do %>
  <script>
    $(document).ready(function(){
      var personal_references = <%= raw(@requisition.personal_references.to_json) %>
      ko.applyBindings(new viewModel(personal_references));
    });
  </script>
<% end %>

app/views/requisitions/index.html.erb
<div class="row">
  <div class="col-md-4">
    <h3><%= welcome_message %></h3>
  </div>
  <div class="col-md-6">
    <h3>Solicitudes Elaboradas</h3>
  </div>
  <div class="col-md-2">
    </br>
    <div class="pull-right">
    <%= link_to t('requisitions.buttons.new'), new_requisition_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

<div class="row">
  <table class="table table-bordered table-striped">
    <thead>
      <th><%= t('requisitions.fields_on_table.income') %></th>
      <th><%= t('requisitions.fields_on_table.address_years') %></th>
      <th><%= t('requisitions.fields_on_table.company_years') %></th>
      <th><%= t('requisitions.fields_on_table.marital_status') %></th>
      <th><%= t('requisitions.fields_on_table.requested_amount') %></th>
      <th><%= t('requisitions.fields_on_table.payment_terms') %></th>
      <th><%= t('requisitions.fields_on_table.bank') %></th>
      <th><%= t('requisitions.fields_on_table.comment') %></th>
      <th><%= t('requisitions.fields_on_table.company_name') %></th>
      <th><%= t('requisitions.fields_on_table.company_phone_number') %></th>
      <th><%= t('requisitions.fields_on_table.dependents_number') %></th>
      <th><%= t('requisitions.fields_on_table.company_position') %></th>
      <th><%= t('requisitions.fields_on_table.has_sgmm') %></th>
      <th><%= t('requisitions.fields_on_table.has_imss') %></th>
      <th><%= t('requisitions.fields_on_table.has_car') %></th>
      <th><%= t('requisitions.actions.action') %></th>

    </thead>
    <tbody>
      <% @requisitions.each do |requisition| %>
        <tr>
          <td><%= requisition.income %></td>
          <td><%= requisition.address_years %></td>
          <td><%= requisition.company_years %></td>
          <td><%= options_of_marital_status.index(requisition.marital_status) %></td>
          <td><%= requisition.requested_amount %></td>
          <td><%= requisition.payment_terms %></td>
          <td><%= requisition.bank %></td>
          <td><%= requisition.comment %></td>
          <td><%= requisition.company_name %></td>
          <td><%= requisition.company_phone_number %></td>
          <td><%= requisition.dependents_number %></td>
          <td><%= requisition.company_position %></td>
          <td><%= boolean_options.index(requisition.has_sgmm) %></td>
          <td><%= boolean_options.index(requisition.has_imss) %></td>
          <td><%= boolean_options.index(requisition.has_car) %></td>
          <td><%= link_to t('requisitions.actions.edit'), edit_requisition_path(requisition.id), class: 'btn btn-info' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/requisitions/new.html.erb
<div class="row">
  <div class="col-12">
    <h2 class="bd-title"><%= t('requisitions.messages.new_instructions') %></h2>
  </div>
</div>
<div class="row">
  <div class="col-12 col-md-9 pull-md-3 bd-content">
    <%= render "form" %>
  </div>
</div>
<% content_for :javascript_bottom do %>
  <script>
    $(document).ready(function(){
      ko.applyBindings(new viewModel([]));
    });
  </script>
<% end %>